import 'package:project_a/models/achievements_model.dart';

List<Achievement> achList = [
  Achievement("BFFs", "As Portugal, join the same faction as Great Britain."),
  Achievement(
      "Braaaaains!", "As Canada, complete the Send in the Zombies focus."),
  Achievement("Canada First", "Join Axis as Canada."),
  Achievement(
      "District 9", "As South Africa, have 9 civilian factories in Transvaal."),
  Achievement("Do You Mined?",
      "Lay at least 1,000 mines on the coastline of an enemy nation."),
  Achievement("Friend in Need", "Join a faction."),
  Achievement("Hellenic Civility", "Win the Greek Civil War before 1937."),
  Achievement("Hoofin’ It", "Unite Arabia with thirty camelry divisions."),
  Achievement("I SEE EVERYTHING",
      "Get over 90% intel in each category on a major without using code cracking."),
  Achievement("Lethal Straight",
      "Have a production license from at least 5 of the 7 major powers."),
  Achievement("Listen Very Carefully, I Shall Say This...",
      "Have a French and British spy work together on the same Operation."),
  Achievement("Man of a Thousand Faces, Every One the Same",
      "Have the same spy get captured twice."),
  Achievement(
      "Mine is bigger than yours", "Lead a faction with at least 20 members."),
  Achievement("No country for old men",
      "Reach 0 manpower with Scraping the Barrel as Conscription Law."),
  Achievement(
      "Nobody’s Business but the Turks", "Restore the Ottoman Sultanate."),
  Achievement("Nothing Wrong with our Bloody Ships",
      "As the United Kingdom, have at least 9 battlecruisers."),
  Achievement("One Nation Under Atatürk, Indivisible",
      "As non-aligned Turkey, have zero negative state modifiers."),
  Achievement("Peter’s Pride",
      "As Peter II of Yugoslavia, overthrow your uncle and become King."),
  Achievement("Play It, Sam",
      "Have a spy network of at least 50% strength in Casablanca."),
  Achievement("Romance of the Three Kingdoms",
      "As China, puppet and then annex Yunnan and Guangxi Clique."),
  Achievement("Shaken, Not Stirred",
      "Successfully stage a coup in any nation using a spy with the Seducer trait."),
  Achievement("Spies Trade", "As India, become the spymaster for the Allies."),
  Achievement("The Balkan Powder Keg",
      "As Yugoslavia, start the Second World War (i.e. be part of either the Axis or the Allies and at war with the other faction in a war you started)."),
  Achievement("Time is on our side", "Reach 1948."),
  Achievement("To Arms in Dixie!",
      "As the U.S.A., start a new civil war as the South."),
  Achievement("Transport Tycoon", "Have at least 1000 convoys."),
  Achievement("Turing Complete!", "Fully decrypt all nations in the Axis."),
  Achievement(
      "United Netherlands", "Conquer Belgium and Luxembourg as Netherlands."),
  Achievement("We'll Build it in a Day", "Research Construction V."),
  Achievement("You Will Never Kill Me Alive",
      "Have one of your spies take a Suicide Pill."),
  Achievement("Arsenal of Democracy",
      "As the U.S.A., have more than 300 military factories."),
  Achievement(
      "Australia-Hungary", "As Australia, own all core territory of Hungary."),
  Achievement("Better than the Szent István",
      "As Hungary, have Miklos Horthy as a Naval commander and build a battleship."),
  Achievement("Britzkrieg",
      "As the United Kingdom, put Edward VIII in power, ally Germany and fully control Paris."),
  Achievement("Cut The Strings", "Break free from your overlord as a puppet."),
  Achievement("Destroyer of Worlds", "Deploy a nuke."),
  Achievement("En Svensk Tiger",
      "As Sweden, acquire a production license for a Tiger or Tiger II tank from Germany."),
  Achievement("I Am the Tong Master",
      "As South Africa, break free from the UK and puppet another nation."),
  Achievement(
      "I Captured the Bosporus and All I Got Was This Lousy Achievement",
      "As Greece or Bulgaria, own both sides of the Bosporus. As Turkey, subjugate both Greece & Bulgaria."),
  Achievement("Istanbul is Constantinople. Again.",
      "As Greece, capture Istanbul and rename it to Constantinople."),
  Achievement("Make a Man Out Of You",
      "As a Warlord, have at least 1,000,000 manpower queued up for deployment."),
  Achievement(
      "Master of War", "Fully research a land, naval and air doctrine tree."),
  Achievement("Mi Casa es tu Casa", "As Mexico, host a government-in-exile."),
  Achievement("Monarchy is Back in Fashion",
      "As Germany, Bring back the Kaiser and ensure that Italy is controlled by Victor Emmanuel by killing Mussolini."),
  Achievement("Now This is Getting Childish",
      "As Yugoslavia or Bulgaria, be at war while both countries are ruled by a child."),
  Achievement("Our Words Are Backed With Nuclear Weapons",
      "As India, develop and deploy a nuke. You must have the Quit India Movement national spirit."),
  Achievement("Panda-monium",
      "As a warlord, be at war with all Chinese nations simultaneously."),
  Achievement("Second Time’s the Charm",
      "As France, occupy Moscow while Napoleon VI is your country leader."),
  Achievement("Team America", "As the U.S.A., drop a nuclear bomb on Paris."),
  Achievement("The Empire Strikes Back",
      "As Britain, declare war on one of your former subjects."),
  Achievement("This is Madness!",
      "As Greece, fulfil the Megali Idea and then form Greater Greece."),
  Achievement("Tojo Shot First",
      "As Japan, Nuke a core territory of the US before the US develops nuclear weapons."),
  Achievement("Totally Not Cool, Bromania",
      "As Romania, change sides in the war and capitulate a former ally."),
  Achievement("Tour de France",
      "Occupy all of mainland France while having at least 20 fully equipped Bicycle regiments."),
  Achievement("Underpaid, Undersexed, and Under Eisenhower",
      "As the U.S.A., assume faction leadership of the Allies, and have over 50 expeditionary divisions from the United Kingdom."),
  Achievement("Vive la France",
      "Reach 1948 as France without capitulating or surrendering."),
  Achievement("Vive la Jeune Ecole",
      "As France, have at least 150 Destroyers and research the maximum torpedo launcher technology, before 1945."),
  Achievement("Warszawo, Walcz!", "Stage the Warsaw uprising and succeed."),
  Achievement(
      "Wunderwaffen", "Research all rocket, nuclear and jet technologies."),
  Achievement("Assuming Direct Control",
      "Starting as a minor power, assume faction leadership of the Allies, the Axis, or the Comintern."),
  Achievement("Balkan Problem Solved",
      "As Communist Bulgaria, form the United Balkan Federation and own all Balkan states as cores."),
  Achievement("Crusader Kings",
      "As South Africa, finish the A King for our People focus and take Jerusalem."),
  Achievement("Crush the Dream",
      "As a Communist United Kingdom, crush the American Dream by puppeting the U.S.A."),
  Achievement("Dracula’s Revenge",
      "As Yugoslavia, establish the autonomous region of Transylvania and have it own all Romanian cores."),
  Achievement("Forge of Victory", "Have 50 factories as Belgium."),
  Achievement("Freedom or Death",
      "As Greece, liberate Albania while being at war with Italy."),
  Achievement("Freegypt",
      "As Egypt, go from puppet to a free nation using the autonomy system."),
  Achievement("History Repeated Itself",
      "As the U.S.A., Win against the Confederate States. Again."),
  Achievement("House of Kurds", "As Kurdistan, hold all of your cores."),
  Achievement("Last for a Thousand Years",
      "As the United Kingdom, accomplish the federation of the entire British Empire."),
  Achievement(
      "Made in China", "As Communist China, have over 100 military factories."),
  Achievement("Master Puppeteer",
      "As Bulgaria, complete the focus The Fate of the Balkans while having 5 or more Balkan puppets."),
  Achievement("My Ships Don't Lie",
      "As Colombia, form Gran Colombia and have 10 Carriers and 10 Battleships."),
  Achievement("Nobody expects...",
      "As Nationalist Spain in Axis manage to take Paris before the Germans."),
  Achievement("Northern Light",
      "As a Scandinavian country form your own faction, and have Denmark, Sweden, Norway and Finland in it."),
  Achievement("Once More Mate", "Occupy Gallipoli as Australia."),
  Achievement("Our Chief Weapon is Surprise...",
      "As Spain, have at least 5 spies and stage 5 coups against other nations."),
  Achievement("Our Other Place in the Sun",
      "As Imperial Germany, conquer a Caribbean island."),
  Achievement(
      "Poland Can Into Space", "Finish all Rocket Technologies as Poland."),
  Achievement(
      "Pride and Extreme Prejudice", "Sink the British Pride of the Fleet."),
  Achievement(
      "The bell tolls for us", "Win Spanish Civil War as Republican Spain."),
  Achievement("The Good, the Bad and the Weird",
      "As Manchukuo, have max level infrastructure in every owned state and generate at least 15 units of oil."),
  Achievement("The Munich Disagreement",
      "As Czechoslovakia, occupy Munich while at war with Germany."),
  Achievement("The Puppetmaster", "Have at least 51 subjects."),
  Achievement(
      "The Revolution Triumphant", "Have Germany as a puppet of Soviet."),
  Achievement("True Blitzkrieg",
      "As Germany have both Poland and France surrender before January 1st 1940."),
  Achievement("We Will Rock You", "As Spain, own Gibraltar."),
  Achievement("Well, I Didn’t Vote for You",
      "Win the Spanish Civil War as the Anarchists."),
  Achievement("We’re Putting the Band Back Together",
      "As Turkey, be in a faction with Germany and Austria-Hungary."),
  Achievement("Why Die For Danzig?",
      "As Germany, turn France fascist and occupy Danzig without going to war with France."),
  Achievement("William Wallis",
      "As the United Kingdom, put Edward VIII in power, enforce an American monarchy, and have both it and Scotland as subjects."),
  Achievement("Awake and Angry",
      "As China, reconquer all of China and Manchuria and force a Japanese surrender."),
  Achievement("Bearer of Artillery", "Gain Vojtek as commander."),
  Achievement("Big Entente",
      "As France, complete the 'Little Entente' National Focus, and have all German cores owned by you or someone in your faction."),
  Achievement("Die, Perfidious Albion!",
      "As Fascist France or Vichy France, occupy all of Great Britain."),
  Achievement("Don’t Die for Your Country",
      "As Germany in a 1939 start, occupy all of Poland and France without taking more than 475 casualties."),
  Achievement("Duce Nuked'em", "Nuke Los Angeles as fascist Italy."),
  Achievement("Finnish Him!",
      "As Finland, defeat the Soviet Union without joining a faction."),
  Achievement("Georgia On My Mind",
      "As the U.S.A., own and fully control all three Georgias."),
  Achievement("Hail to the Qing", "As Manchukuo, restore the Qing dynasty."),
  Achievement(
      "I Swear I'm Not a Byzantophile", "As Greece, Form Byzantine Empire."),
  Achievement(
      "It's 1812 All Over Again", "As Canada, take and hold Washington D.C."),
  Achievement("Med plutonium...", "Nuke Denmark as Sweden."),
  Achievement("Neither Death nor Dishonor",
      "As Romania, make it to 1942 with all the states you started it with and control either Moscow or Berlin."),
  Achievement("New World Order", "Make all nations fascist."),
  Achievement("One Empire", "Unite the entire world under the British Empire."),
  Achievement("Operation Sea Lion", "Control British mainland as Germany."),
  Achievement("Party like it's 1520", "Occupy Stockholm as communist Denmark."),
  Achievement("Prussia of the Balkans",
      "As Bulgaria capitulate Turkey while also controlling the rest of the Balkans, including Greece."),
  Achievement("Putting the Raid on the Medway to Shame",
      "As the Netherlands, ensure the United Kingdom has no capital ships (carriers, battleships, battlecruisers, or heavy cruisers)."),
  Achievement(
      "Sunrise Invasion", "As Japan, conquer Mexico then Europe before 1945."),
  Achievement("Sunset Invasion",
      "Occupy a coastal province in Europe as Mexico, and if in a faction have it contain only South American members or puppets."),
  Achievement("The New Home of the Revolution",
      "As Mexico, put Trotsky in power and puppet the Soviet Union"),
  Achievement("The Revenge of Montezuma",
      "Restore the old borders with the USA as Mexico."),
  Achievement("The Dragon Swallowed the Sun",
      "As Manchukuo, Break free from Japan and annex your former Overlord without being in a faction."),
  Achievement("Treading the Narrow Path",
      "As the Netherlands, do not cave to the Germans, continue the Zuiderzee works, and do not lose control of any of your continental European states until 1945."),
  Achievement("Bad Romeance",
      "Restore Byzantium and have Italy, Romania, and Russia as subjects."),
  Achievement("Battlecry", "As a warlord, conquer all of China and Japan."),
  Achievement("Bevrijding",
      "As the Netherlands, liberate the continental Netherlands after relocating the government to the East Indies."),
  Achievement("Czechmate",
      "As Czechoslovakia, occupy Canberra while at war with the Allies."),
  Achievement("Death or Dishonor or Cake",
      "As Romania, own a slice of all your starting neighbors."),
  Achievement("Go Ahead, Macau My Day",
      "As Portugal, create a collaboration government in Macau and have it own all Chinese states."),
  Achievement("Hardly Anything Sèvres",
      "As the Ottoman Empire, hold the capitals of France, the United Kingdom, Italy, and Japan."),
  Achievement("Huge-oslavia",
      "As Yugoslavia, occupy all your neighbouring countries (Austria, Hungary, Romania, Bulgaria, Albania, Italy and Greece)."),
  Achievement("Miklos Horthy and the Habsburg Prince",
      "As Hungary, Restore Austria-Hungary."),
  Achievement("One King, Two Crowns",
      "As Bourbon Spain, hold all Spanish and French core states."),
  Achievement("Rule Britannia",
      "As any British Subject state, conquer all of Britain."),
  Achievement(
      "Sun Tzu Reborn", "As Any Chinese Nation, Have a level 9 field marshal."),
  Achievement("The People Have Stood Up!",
      "With Mao as your leader, win the Chinese Civil War."),
  Achievement("The weapons of the Third Emu War",
      "As Australia, use a nuclear bomb on core Australian territory."),
  Achievement("30 Minutes of Hel",
      "As Poland in the 1939 “Blitzkrieg” scenario start, inflict over 1,800,000 casualties to Germany to beat the 2018 PDXCON HOI4 challenge. Extra bragging rights if you do it in 30 minutes or less!"),
  Achievement("Crusader Kings 2",
      "As South Africa, finish the Anti-Colonialist Crusade focus, release all European colonies via the focus, and take London."),
  Achievement("At least they run on time!",
      "As fascist Italy, have max level railways in all your core states"),
  Achievement("Not much fun in Stalingrad",
      "As Germany, capitulate the Soviet Union without taking Stalingrad."),
  Achievement("No more Partitions",
      "As Poland, be independent and ensure that both Germany and the USSR are either in your faction or don’t exist."),
  Achievement("Habsburgs. Habsburgs everywhere",
      "As Poland, install a Habsburg monarch and be in a faction with another Habsburg monarch."),
  Achievement(
      "The Pope? How many Divisions does he have?", "As the USSR take Rome."),
  Achievement("This is going to be LIT",
      "As Lithuania, hold the capitals of all of your neighbours."),
  Achievement("It has my name on it",
      "As any Baltic State, conquer the entire shoreline of the Baltic Sea."),
  Achievement("This Achievement is Cheesy",
      "As Latvia, form Ostland and occupy Vasterbotten."),
  Achievement("Esti is Scandi", "As Estonia Secure Scandinavia."),
  Achievement("Not a step back!",
      "As the Soviet Union never lose 1 core territory to anyone before 1945."),
  Achievement("One Step Forward",
      "As Soviet Union declare a war on Poland and Germany before Germany attacks Poland."),
  Achievement("The Soviet Onion",
      "As the Soviet Union, have only puppets as neighbors."),
  Achievement("Crusader Kings III",
      "As Poland, crown a King (or Queen) and capture Jerusalem."),
  Achievement("The Romanovs laugh last",
      "Restore the Romanovs to the throne and conquer Germany, Hungary, Austria, Czechoslovakia, Turkey, and Bulgaria."),
  Achievement("We don't really like statistics",
      "As the Soviet Union under Stalin, conquer Germany while suffering less than 1 million casualties total."),
  Achievement("Race for Germany",
      "As the Soviet union, capitulate Germany after the fall of France before the allies control one German core state."),
  Achievement("Siberian Tiger", "As Tannu Tuva, form Siberia."),
  Achievement("Just proper gander",
      "As the Soviet Union, activate 30 propaganda campaigns before 1945."),
  Achievement("Around Eurasia in 80 days",
      "Make a railroad from Gibraltar to Singapore."),
  Achievement("Poland Peasant Revolution",
      "As Poland, have the Peasant’s Strike overthrow the government."),
];
